import { AnalysisResult } from './lib/github/types';

export function generateMarkdownReport(username: string, result: AnalysisResult): string {
  const { graph, recommendations, insights } = result;
  const lines: string[] = [];

  lines.push(`## 🌌 GitHub Social Graph — @${username}`);
  lines.push('');
  lines.push(
    '> Auto-generated by [GitHub Social Graph Action](https://github.com/marketplace/actions/github-social-graph) · 由 [GitHub Social Graph Action](https://github.com/marketplace/actions/github-social-graph) 自动生成'
  );
  lines.push('');

  // Overview / 概览
  lines.push('### 📊 Overview / 社交网络概览');
  lines.push('');
  lines.push('| Metric / 指标 | Value / 数值 |');
  lines.push('|---|---|');
  lines.push(`| 👥 Developers / 开发者节点 | ${graph.stats.userNodes} |`);
  lines.push(`| 📦 Repositories / 仓库节点 | ${graph.stats.repoNodes} |`);
  lines.push(`| 🔗 Connections / 关系连接 | ${graph.stats.totalLinks} |`);
  lines.push(`| 🌐 Total Nodes / 总节点数 | ${graph.stats.totalNodes} |`);
  lines.push('');

  // Language distribution / 编程语言分布
  const langs = Object.entries(insights.languageDistribution ?? {})
    .sort((a, b) => b[1] - a[1])
    .slice(0, 8);
  if (langs.length > 0) {
    lines.push('### 💻 Languages / 编程语言分布');
    lines.push('');
    lines.push(langs.map(([lang, count]) => `\`${lang}\` ×${count}`).join('  '));
    lines.push('');
  }

  // Top collaborators / 顶级协作者
  if (insights.topCollaborators?.length > 0) {
    lines.push('### 🤝 Top Collaborators / 顶级协作者');
    lines.push('');
    for (const { user, collaborations } of insights.topCollaborators.slice(0, 5)) {
      lines.push(
        `- [![avatar](https://avatars.githubusercontent.com/${user.login}?s=20&v=4)](https://github.com/${user.login}) [@${user.login}](https://github.com/${user.login}) — ${collaborations} contributions / 次贡献`
      );
    }
    lines.push('');
  }

  // Recommended developers / 推荐开发者
  if (recommendations?.length > 0) {
    lines.push('### 🎯 Recommended Developers / 推荐关注的开发者');
    lines.push('');
    lines.push(
      'Based on collaboration patterns, you may be interested in: / 基于协作关系分析，以下开发者可能与你有共同兴趣：'
    );
    lines.push('');
    for (const rec of recommendations.slice(0, 6)) {
      lines.push(
        `- [![avatar](https://avatars.githubusercontent.com/${rec.user.login}?s=20&v=4)](https://github.com/${rec.user.login}) [@${rec.user.login}](https://github.com/${rec.user.login}) — ${rec.reasons[0] ?? ''}`
      );
    }
    lines.push('');
  }

  // Top starred repos / 最受欢迎的仓库
  if (insights.topStarredRepos?.length > 0) {
    lines.push('### ⭐ Top Repositories / 最受欢迎的仓库');
    lines.push('');
    for (const { repo, stargazers } of insights.topStarredRepos.slice(0, 5)) {
      const desc = repo.description ? `  \n  ${repo.description}` : '';
      lines.push(`- [${repo.full_name}](${repo.html_url}) — ⭐ ${stargazers}${desc}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Generated at / 分析时间: ${new Date().toISOString()}*`);

  return lines.join('\n');
}
